name: Bug Report
description: テンプレート
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: 環境
      description: 実行していたソフトウェアの環境は?
      options:
        - 本番
        - 開発
        - テスト
    validations:
      required: true
  - type: dropdown
    id: couse-deploy
    attributes:
      label: 障害原因
      description: デプロイが原因ですか?
      options:
        - deploy
        - deploy以外
    validations:
      required: true
  - type: input
    id: cause
    attributes:
      description: 障害原因がDeployの場合、きっかけとなった PR のリンクを貼ってください。（例：#1）
      placeholder: "#0"
    validations:
      required: true
  - type: input
    id: when-happened
    attributes:
      label: 障害発生時刻
      description: yyyy-mm-dd hh:mm で記入してください。
      placeholder: 0000-00-00 00:00
    validations:
      required: true
  - type: input
    id: when-looked
    attributes:
      label: 障害検知時刻
      description: yyyy-mm-dd hh:mm で記入してください。
      placeholder: 0000-00-00 00:00
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: サービス復元時刻
      description: yyyy-mm-dd hh:mm で記入してください。
      placeholder: 0000-00-00 00:00
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: 関連するログの出力をコピーしてペーストしてください。 これは自動的にコードにフォーマットされるので、バックティックは不要です。
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: このIssueをサブミットすることで、あなたは私たちの [行動規範](https://example.com)に同意したことになります。
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
