# Generated by Django 3.1.2 on 2021-09-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenderSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kalender',
            new_name='Calender',
        ),
    ]
