# Generated by Django 3.1.2 on 2021-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
