# Generated by Django 3.2.9 on 2021-12-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 14, 18, 21, 671509)),
        ),
    ]
