# Generated by Django 2.1.7 on 2021-11-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AlterField(
            model_name='task',
            name='contents',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
