# Generated by Django 3.2.9 on 2021-12-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0002_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 14, 24, 48, 69707)),
        ),
    ]
