# Generated by Django 2.1.7 on 2021-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0002_auto_20211109_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=''),
        ),
    ]
