# Generated by Django 3.2.9 on 2021-12-14 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0002_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 11, 42, 49, 934107)),
        ),
        migrations.AlterField(
            model_name='user_subject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarSite.subject'),
        ),
    ]
