# Generated by Django 3.2.9 on 2021-12-13 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0003_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 12, 10, 25, 741730)),
        ),
        migrations.CreateModel(
            name='Subject_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarSite.subject')),
            ],
        ),
    ]
