# Generated by Django 3.2.9 on 2021-12-14 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0003_auto_20211214_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 11, 54, 28, 467008)),
        ),
        migrations.AlterField(
            model_name='user_subject',
            name='subject_id',
            field=models.CharField(max_length=200),
        ),
    ]
