# Generated by Django 3.2.9 on 2021-12-13 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0004_auto_20211213_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subject',
            name='period',
        ),
        migrations.RemoveField(
            model_name='user_subject',
            name='week',
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 13, 48, 50, 420582)),
        ),
    ]
