# Generated by Django 2.1.7 on 2021-11-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0004_auto_20211109_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
