# Generated by Django 3.2.9 on 2021-12-13 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0005_auto_20211213_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 13, 49, 4, 842869)),
        ),
    ]
