# Generated by Django 2.1.7 on 2021-11-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0007_auto_20211107_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject_id',
            field=models.ForeignKey(help_text='科目名', on_delete=django.db.models.deletion.CASCADE, to='calendarSite.Subject'),
        ),
    ]
